apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-grafana
  labels:
    name: {{ include "app.fullname" . }}-grafana
data:
  grafana.ini: |
    [paths]
    plugins = /var/lib/grafana/plugins
    
    [auth.basic]
    enabled = false

    [users]
    allow_sign_up = true
    allow_org_create = true
    
    [auth.keystone]
    enabled = true
    verify_ssl_cert = false
    v3 = true
    default_domain = Default
    
    [log.console]
    level = trace
    
    [database]
    type = mysql
    name = grafana
    ssl_mode = disable