apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-grafana
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
    - name: "grafana"
      port: 3000
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}