apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-prometheus
  annotations:
    dev.okteto.com/auto-ingress: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port:   "9090"
spec:
  type: ClusterIP  
  ports:
  - name: "prometheus"
    port: 9090
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}