apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-prometheus
  labels:
    name: {{ include "app.fullname" . }}-prometheus
data:
  prometheus.rules: |-
    groups:
    - name: alert
      rules:
      - alert: MysqlDown
        expr: mysql_up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: MySQL down
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs:
      - job_name: 'tech-exam-app-prometheus-monitoring'
        static_configs:
        - targets:
          - tech-exam-prom-mysql-exporter-prometheus-mysql-exporter:9104